// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bakalarska_praca.Models;

namespace bakalarska_praca.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210320092622_refreshToken")]
    partial class refreshToken
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("bakalarska_praca.Models.Attack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dest_ip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("SeverityCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Src_ip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Attacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "SQL",
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "TCP",
                            Severity = 3,
                            SeverityCategory = "low",
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2021, 2, 20, 14, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Category = "ICMP",
                            Dest_ip = "192.168.40.183",
                            Message = "Possible ICMP flood PING DoS",
                            Proto = "TCP",
                            Severity = 10,
                            SeverityCategory = "critical",
                            Src_ip = "192.168.50.11",
                            Timestamp = new DateTime(2021, 2, 21, 14, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Category = "SQL",
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "UDP",
                            Severity = 3,
                            SeverityCategory = "low",
                            Src_ip = "192.168.50.11",
                            Timestamp = new DateTime(2021, 2, 22, 14, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Category = "ICMP",
                            Dest_ip = "192.168.40.183",
                            Message = "Possible ICMP flood PING DoS",
                            Proto = "TCP",
                            Severity = 4,
                            SeverityCategory = "medium",
                            Src_ip = "192.168.60.11",
                            Timestamp = new DateTime(2021, 2, 23, 14, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Category = "SQL",
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "TCP",
                            Severity = 4,
                            SeverityCategory = "medium",
                            Src_ip = "192.168.60.11",
                            Timestamp = new DateTime(2021, 2, 24, 14, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Category = "SYN",
                            Dest_ip = "192.168.60.183",
                            Message = "Possible TCP SYN DoS",
                            Proto = "TCP",
                            Severity = 2,
                            SeverityCategory = "low",
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2021, 2, 25, 14, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            Category = "SQL",
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "TCP",
                            Severity = 1,
                            SeverityCategory = "low",
                            Src_ip = "192.168.60.11",
                            Timestamp = new DateTime(2021, 2, 26, 14, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            Category = "ICMP",
                            Dest_ip = "192.168.40.183",
                            Message = "Possible ICMP flood PING DoS",
                            Proto = "UDP",
                            Severity = 4,
                            SeverityCategory = "medium",
                            Src_ip = "192.168.20.11",
                            Timestamp = new DateTime(2021, 2, 27, 14, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            Category = "SQL",
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "TCP",
                            Severity = 3,
                            SeverityCategory = "low",
                            Src_ip = "192.168.30.11",
                            Timestamp = new DateTime(2021, 2, 28, 14, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            Category = "SQL",
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "TCP",
                            Severity = 2,
                            SeverityCategory = "low",
                            Src_ip = "192.168.20.11",
                            Timestamp = new DateTime(2021, 3, 1, 14, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            Category = "UDP",
                            Dest_ip = "192.168.40.183",
                            Message = "Possible UDP DoS",
                            Proto = "TCP",
                            Severity = 6,
                            SeverityCategory = "medium",
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2021, 3, 2, 14, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            Category = "ICMP",
                            Dest_ip = "192.168.40.183",
                            Message = "Possible ICMP flood PING DoS",
                            Proto = "TCP",
                            Severity = 7,
                            SeverityCategory = "high",
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2021, 3, 3, 14, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            Category = "SQL",
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "TCP",
                            Severity = 5,
                            SeverityCategory = "medium",
                            Src_ip = "192.168.20.11",
                            Timestamp = new DateTime(2021, 3, 4, 14, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            Category = "SQL",
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "UDP",
                            Severity = 7,
                            SeverityCategory = "high",
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2021, 3, 5, 14, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            Category = "SYN",
                            Dest_ip = "192.168.40.183",
                            Message = "Possible TCP SYN DoS",
                            Proto = "TCP",
                            Severity = 2,
                            SeverityCategory = "low",
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2021, 3, 6, 14, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            Category = "SQL",
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "TCP",
                            Severity = 1,
                            SeverityCategory = "low",
                            Src_ip = "192.168.30.11",
                            Timestamp = new DateTime(2021, 3, 7, 14, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            Category = "ICMP",
                            Dest_ip = "192.168.40.183",
                            Message = "Possible ICMP flood PING DoS",
                            Proto = "UDP",
                            Severity = 4,
                            SeverityCategory = "medium",
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2021, 3, 8, 14, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            Category = "SQL",
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "TCP",
                            Severity = 9,
                            SeverityCategory = "critical",
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2021, 3, 9, 14, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            Category = "UDP",
                            Dest_ip = "192.168.50.183",
                            Message = "Possible UDP DoS",
                            Proto = "TCP",
                            Severity = 2,
                            SeverityCategory = "low",
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2021, 3, 10, 14, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20,
                            Category = "SQL",
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "TCP",
                            Severity = 8,
                            SeverityCategory = "high",
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2021, 3, 11, 14, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 21,
                            Category = "ICMP",
                            Dest_ip = "192.168.40.183",
                            Message = "Possible ICMP flood PING DoS",
                            Proto = "TCP",
                            Severity = 7,
                            SeverityCategory = "high",
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2021, 3, 12, 9, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 22,
                            Category = "SQL",
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "UDP",
                            Severity = 1,
                            SeverityCategory = "low",
                            Src_ip = "192.168.60.11",
                            Timestamp = new DateTime(2021, 3, 13, 14, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 23,
                            Category = "SYN",
                            Dest_ip = "192.168.40.183",
                            Message = "Possible TCP SYN DoS",
                            Proto = "TCP",
                            Severity = 9,
                            SeverityCategory = "critical",
                            Src_ip = "192.168.70.11",
                            Timestamp = new DateTime(2021, 3, 14, 0, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 24,
                            Category = "SQL",
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "TCP",
                            Severity = 8,
                            SeverityCategory = "high",
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2021, 3, 14, 4, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 25,
                            Category = "ICMP",
                            Dest_ip = "192.168.40.183",
                            Message = "Possible ICMP flood PING DoS",
                            Proto = "TCP",
                            Severity = 7,
                            SeverityCategory = "high",
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2021, 3, 14, 9, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 26,
                            Category = "SQL",
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "UDP",
                            Severity = 1,
                            SeverityCategory = "low",
                            Src_ip = "192.168.60.11",
                            Timestamp = new DateTime(2021, 3, 14, 9, 45, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 27,
                            Category = "SYN",
                            Dest_ip = "192.168.40.183",
                            Message = "Possible TCP SYN DoS",
                            Proto = "TCP",
                            Severity = 9,
                            SeverityCategory = "critical",
                            Src_ip = "192.168.70.11",
                            Timestamp = new DateTime(2021, 3, 14, 20, 17, 49, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("bakalarska_praca.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Logins");
                });
#pragma warning restore 612, 618
        }
    }
}
