// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bakalarska_praca.Models;

namespace bakalarska_praca.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210123143355_mockData")]
    partial class mockData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("bakalarska_praca.Models.Attack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Dest_ip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("Src_ip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Attacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "TCP",
                            Severity = 3,
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2020, 10, 21, 15, 17, 49, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "TCP",
                            Severity = 3,
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2020, 10, 22, 15, 17, 49, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "TCP",
                            Severity = 3,
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2020, 10, 23, 15, 17, 49, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
