// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bakalarska_praca.Models;

namespace bakalarska_praca.Migrations
{
    /// <summary>DbContext <c>AppDbContextModelSnapshot</c> creates snapshot (auto generated)</summary>
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("bakalarska_praca.Models.Attack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dest_ip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("SeverityCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Src_ip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Attacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "SQL",
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "TCP",
                            Severity = 3,
                            SeverityCategory = "low",
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2021, 3, 20, 14, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Category = "ICMP",
                            Dest_ip = "192.168.40.183",
                            Message = "Possible ICMP flood PING DoS",
                            Proto = "TCP",
                            Severity = 10,
                            SeverityCategory = "critical",
                            Src_ip = "192.168.50.11",
                            Timestamp = new DateTime(2021, 3, 20, 9, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Category = "SQL",
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "UDP",
                            Severity = 3,
                            SeverityCategory = "low",
                            Src_ip = "192.168.50.11",
                            Timestamp = new DateTime(2021, 3, 20, 14, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Category = "ICMP",
                            Dest_ip = "192.168.40.183",
                            Message = "Possible ICMP flood PING DoS",
                            Proto = "TCP",
                            Severity = 4,
                            SeverityCategory = "medium",
                            Src_ip = "192.168.60.11",
                            Timestamp = new DateTime(2021, 3, 23, 14, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Category = "SQL",
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "TCP",
                            Severity = 4,
                            SeverityCategory = "medium",
                            Src_ip = "192.168.60.11",
                            Timestamp = new DateTime(2021, 3, 24, 14, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Category = "SYN",
                            Dest_ip = "192.168.60.183",
                            Message = "Possible TCP SYN DoS",
                            Proto = "TCP",
                            Severity = 2,
                            SeverityCategory = "low",
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2021, 3, 25, 7, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            Category = "SQL",
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "TCP",
                            Severity = 1,
                            SeverityCategory = "low",
                            Src_ip = "192.168.60.11",
                            Timestamp = new DateTime(2021, 3, 25, 14, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            Category = "ICMP",
                            Dest_ip = "192.168.40.183",
                            Message = "Possible ICMP flood PING DoS",
                            Proto = "UDP",
                            Severity = 4,
                            SeverityCategory = "medium",
                            Src_ip = "192.168.20.11",
                            Timestamp = new DateTime(2021, 4, 5, 13, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            Category = "SQL",
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "TCP",
                            Severity = 3,
                            SeverityCategory = "low",
                            Src_ip = "192.168.30.11",
                            Timestamp = new DateTime(2021, 4, 5, 17, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            Category = "SQL",
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "TCP",
                            Severity = 2,
                            SeverityCategory = "low",
                            Src_ip = "192.168.20.11",
                            Timestamp = new DateTime(2021, 4, 5, 13, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            Category = "UDP",
                            Dest_ip = "192.168.40.183",
                            Message = "Possible UDP DoS",
                            Proto = "TCP",
                            Severity = 6,
                            SeverityCategory = "medium",
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2021, 4, 9, 13, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            Category = "ICMP",
                            Dest_ip = "192.168.40.183",
                            Message = "Possible ICMP flood PING DoS",
                            Proto = "TCP",
                            Severity = 7,
                            SeverityCategory = "high",
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2021, 4, 10, 12, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            Category = "SQL",
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "TCP",
                            Severity = 5,
                            SeverityCategory = "medium",
                            Src_ip = "192.168.20.11",
                            Timestamp = new DateTime(2021, 4, 10, 13, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            Category = "SQL",
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "UDP",
                            Severity = 7,
                            SeverityCategory = "high",
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2021, 4, 11, 13, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            Category = "SYN",
                            Dest_ip = "192.168.40.183",
                            Message = "Possible TCP SYN DoS",
                            Proto = "TCP",
                            Severity = 2,
                            SeverityCategory = "low",
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2021, 4, 11, 13, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            Category = "SQL",
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "TCP",
                            Severity = 1,
                            SeverityCategory = "low",
                            Src_ip = "192.168.30.11",
                            Timestamp = new DateTime(2021, 4, 12, 13, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            Category = "ICMP",
                            Dest_ip = "192.168.40.183",
                            Message = "Possible ICMP flood PING DoS",
                            Proto = "UDP",
                            Severity = 4,
                            SeverityCategory = "medium",
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2021, 4, 13, 13, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            Category = "SQL",
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "TCP",
                            Severity = 9,
                            SeverityCategory = "critical",
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2021, 4, 14, 13, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            Category = "UDP",
                            Dest_ip = "192.168.50.183",
                            Message = "Possible UDP DoS",
                            Proto = "TCP",
                            Severity = 2,
                            SeverityCategory = "low",
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2021, 4, 15, 13, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20,
                            Category = "SQL",
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "TCP",
                            Severity = 8,
                            SeverityCategory = "high",
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2021, 4, 15, 13, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 21,
                            Category = "ICMP",
                            Dest_ip = "192.168.40.183",
                            Message = "Possible ICMP flood PING DoS",
                            Proto = "TCP",
                            Severity = 7,
                            SeverityCategory = "high",
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2021, 4, 16, 8, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 22,
                            Category = "SQL",
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "UDP",
                            Severity = 1,
                            SeverityCategory = "low",
                            Src_ip = "192.168.60.11",
                            Timestamp = new DateTime(2021, 4, 17, 13, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 23,
                            Category = "SYN",
                            Dest_ip = "192.168.40.183",
                            Message = "Possible TCP SYN DoS",
                            Proto = "TCP",
                            Severity = 9,
                            SeverityCategory = "critical",
                            Src_ip = "192.168.70.11",
                            Timestamp = new DateTime(2021, 4, 17, 23, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 24,
                            Category = "SQL",
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "TCP",
                            Severity = 8,
                            SeverityCategory = "high",
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2021, 4, 19, 3, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 25,
                            Category = "ICMP",
                            Dest_ip = "192.168.40.183",
                            Message = "Possible ICMP flood PING DoS",
                            Proto = "TCP",
                            Severity = 7,
                            SeverityCategory = "high",
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2021, 4, 19, 8, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 26,
                            Category = "SQL",
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "UDP",
                            Severity = 1,
                            SeverityCategory = "low",
                            Src_ip = "192.168.60.11",
                            Timestamp = new DateTime(2021, 4, 20, 8, 45, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 27,
                            Category = "SYN",
                            Dest_ip = "192.168.40.183",
                            Message = "Possible TCP SYN DoS",
                            Proto = "TCP",
                            Severity = 9,
                            SeverityCategory = "critical",
                            Src_ip = "192.168.70.11",
                            Timestamp = new DateTime(2021, 4, 21, 19, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 28,
                            Category = "ICMP",
                            Dest_ip = "192.168.40.183",
                            Message = "Possible ICMP flood PING DoS",
                            Proto = "TCP",
                            Severity = 7,
                            SeverityCategory = "high",
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2021, 4, 22, 8, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 29,
                            Category = "SQL",
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "UDP",
                            Severity = 1,
                            SeverityCategory = "low",
                            Src_ip = "192.168.60.11",
                            Timestamp = new DateTime(2021, 4, 23, 8, 45, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 30,
                            Category = "SYN",
                            Dest_ip = "192.168.40.183",
                            Message = "Possible TCP SYN DoS",
                            Proto = "TCP",
                            Severity = 9,
                            SeverityCategory = "critical",
                            Src_ip = "192.168.70.11",
                            Timestamp = new DateTime(2021, 4, 24, 19, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 31,
                            Category = "ICMP",
                            Dest_ip = "192.168.40.183",
                            Message = "Possible ICMP flood PING DoS",
                            Proto = "TCP",
                            Severity = 7,
                            SeverityCategory = "high",
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2021, 4, 25, 8, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 32,
                            Category = "SQL",
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "UDP",
                            Severity = 1,
                            SeverityCategory = "low",
                            Src_ip = "192.168.60.11",
                            Timestamp = new DateTime(2021, 4, 26, 8, 45, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 33,
                            Category = "SYN",
                            Dest_ip = "192.168.40.183",
                            Message = "Possible TCP SYN DoS",
                            Proto = "TCP",
                            Severity = 9,
                            SeverityCategory = "critical",
                            Src_ip = "192.168.70.11",
                            Timestamp = new DateTime(2021, 4, 28, 23, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 34,
                            Category = "ICMP",
                            Dest_ip = "192.168.40.183",
                            Message = "Possible ICMP flood PING DoS",
                            Proto = "TCP",
                            Severity = 7,
                            SeverityCategory = "high",
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2021, 3, 29, 8, 17, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 35,
                            Category = "SQL",
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "UDP",
                            Severity = 1,
                            SeverityCategory = "low",
                            Src_ip = "192.168.60.11",
                            Timestamp = new DateTime(2021, 3, 29, 17, 45, 49, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 36,
                            Category = "SYN",
                            Dest_ip = "192.168.40.183",
                            Message = "Possible TCP SYN DoS",
                            Proto = "TCP",
                            Severity = 9,
                            SeverityCategory = "critical",
                            Src_ip = "192.168.70.11",
                            Timestamp = new DateTime(2021, 3, 30, 19, 17, 49, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("bakalarska_praca.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Logins");
                });
#pragma warning restore 612, 618
        }
    }
}
