// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bakalarska_praca.Models;

namespace bakalarska_praca.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("bakalarska_praca.Models.Attack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Dest_ip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("Src_ip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Attacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "TCP",
                            Severity = 3,
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2020, 10, 10, 15, 17, 49, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "TCP",
                            Severity = 3,
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2020, 10, 11, 15, 17, 49, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injectio n Detected",
                            Proto = "TCP",
                            Severity = 3,
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2020, 10, 12, 15, 17, 49, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "TCP",
                            Severity = 4,
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2020, 10, 13, 15, 17, 49, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "TCP",
                            Severity = 4,
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2020, 10, 14, 15, 17, 49, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "TCP",
                            Severity = 5,
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2020, 10, 15, 15, 17, 49, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "TCP",
                            Severity = 5,
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2020, 10, 16, 15, 17, 49, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "TCP",
                            Severity = 4,
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2020, 10, 17, 15, 17, 49, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "TCP",
                            Severity = 4,
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2020, 10, 18, 15, 17, 49, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "TCP",
                            Severity = 2,
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2020, 10, 19, 15, 17, 49, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "TCP",
                            Severity = 2,
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2020, 10, 20, 15, 17, 49, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "TCP",
                            Severity = 2,
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2020, 10, 21, 15, 17, 49, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Dest_ip = "192.168.40.183",
                            Message = "Error Based SQL Injection Detected",
                            Proto = "TCP",
                            Severity = 2,
                            Src_ip = "192.168.40.11",
                            Timestamp = new DateTime(2020, 10, 22, 15, 17, 49, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
